### ISSUE TITLE
Concordium contract changes

### ISSUE THREAD

**Issue by abizjak** [Concordium/eth-ccd-bridge#2]
**Task description**

The following auxiliary functions should be added to the concordium bridge manager and token contracts

- [ ] View functions for mapping tokens in Concordium, i.e., see which tokens are mapped to what.
- [ ] See the roles in Concordium contracts, who is admin, who is manager, ...
- [ ] Whether an event index has already been processed or not.
