### ISSUE TITLE
Ethereum contract changes.

### ISSUE THREAD

**Issue by abizjak** [Concordium/eth-ccd-bridge#3]
**Task description**

The following changes in the Ethereum bridge contracts and deployment scripts should be made

- [ ] Fix deployment verification script fails.
- [ ] Fix linking between proxies and contracts so there is no confusion on, e.g., Etherscan.
- [ ] Write description of multi-sig setup.
- [ ] Change concordium transaction hash in withdraw event and withdraw parameters to be `bytes32` instead of String.

**Comment by abizjak** [comment]
Wait with remaining tasks until there is clarity on who runs the bridge.
