### ISSUE TITLE
Relayer changes

### ISSUE THREAD

**Issue by abizjak** [Concordium/eth-ccd-bridge#4]
**Task description**

The tasks related to the relayer rewrite.

**Sub-tasks**
- [x] Implement API server as a separate binary.
  - [x] Implement all endpoints needed by the frontend.
  - [x] Clean up logging.
  - [x] Document configuration.
  - [x] Add simple monitoring setup.
- [x] Proper shutdown signal handling.
- [ ] Documentation of the relayer.
  - [x] Add explanation and scripts on how to generate the ABI
  - [ ] #78
  - [x] Explanation of the metrics.
  - [x] Configuration options in the README.
- [x] Implement reconnects for the concordium side, both for queries and sending transactions.
- [x] Add some retry logic to the connection to infura.
- [x] Log config (non-secret part) on startup of the service.
- [x] Timeouts for Concordium requests.
- [x] Timeouts for Ethereum requests.
- [x] Add metrics via Prometheus to the relayer and API server.
     - [x] Number of pending transactions as a metric.
     - [x] Number of processed deposits and withdrawals since start.
     - [x] Balance of accounts used to send data.
     - [x] Number of errors and warnings.
- [x] Support loading keys from Amazon secret manager.
